export const AUDIT_ACTION_LABELS = {
  create: "Creacion",
  update: "Edicion",
  activate: "Activacion",
  deactivate: "Desactivacion",
  delete: "Eliminacion",
  approve: "Aprobacion",
  reject: "Rechazo",
  cancel: "Cancelacion",
  permissions_change: "Cambio de permisos",
  inventory_adjust: "Ajuste de inventario",
  submit: "Envio a aprobacion",
  return_to_draft: "Devolucion a borrador",
  send_to_production: "Envio a produccion",
  convert_to_quote: "Conversion a cotizacion",
  print: "Impresion",
  progress_update: "Actualizacion de avance",
  complete: "Completado",
  entry: "Entrada de inventario",
  exit: "Salida de inventario",
  transfer: "Transferencia de almacen",
  receive: "Recepcion de compra",
  pdf_generate: "Generacion de PDF",
  report_generate: "Generacion de reporte",
};

export const AUDIT_ACTION_TONES = {
  create: "success",
  update: "brand",
  activate: "success",
  deactivate: "warning",
  delete: "danger",
  approve: "success",
  reject: "danger",
  cancel: "danger",
  permissions_change: "warning",
  inventory_adjust: "brand",
  submit: "brand",
  return_to_draft: "warning",
  send_to_production: "success",
  convert_to_quote: "brand",
  print: "neutral",
  progress_update: "brand",
  complete: "success",
  entry: "success",
  exit: "warning",
  transfer: "brand",
  receive: "success",
  pdf_generate: "neutral",
  report_generate: "neutral",
};

export const AUDIT_MODULE_LABELS = {
  users: "Usuarios",
  roles: "Roles y permisos",
  clients: "Clientes",
  suppliers: "Proveedores",
  warehouses: "Almacenes",
  categories: "Categorias",
  items: "Productos e insumos",
  audit: "Bitacora",
  issuing_companies: "Empresas emisoras",
  manufacturing_processes: "Procesos",
  installation_concepts: "Instalaciones",
  quote_templates: "Biblioteca de items",
  quotes: "Cotizaciones",
  direct_orders: "Ordenes directas",
  production: "Produccion",
  inventory: "Inventario",
  purchase_orders: "Ordenes de compra",
  reports: "Reportes",
  sales: "Dashboard de ventas",
  teams: "Equipos",
};

export const AUDIT_ACTION_OPTIONS = [
  { value: "", label: "Todas las acciones" },
  ...Object.entries(AUDIT_ACTION_LABELS).map(([value, label]) => ({
    value,
    label,
  })),
];

export const AUDIT_MODULE_OPTIONS = [
  { value: "", label: "Todos los modulos" },
  ...Object.entries(AUDIT_MODULE_LABELS).map(([value, label]) => ({
    value,
    label,
  })),
];
